services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    # networks: # Assign to custom network
    #   - my-app-network

  user-service:
    build: ./packages/user-service
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      TOKEN_KEY: ${TOKEN_KEY}
      NODE_ENV: ${NODE_ENV}
      PORT: ${USER_SERVICE_PORT}
    depends_on:
      - postgres

  freelance-service:
    build: ./packages/freelance-service
    ports:
      - "4001:4001"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      NODE_ENV: ${NODE_ENV}
      PORT: ${FREELANCE_SERVICE_PORT}
      USER_SERVICE_URL: http://user-service:4000/auth/validate
    depends_on:
      - postgres
      - user-service

  event-service:
    build: ./packages/event-service
    ports:
      - "4002:4002"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      NODE_ENV: ${NODE_ENV}
      PORT: ${EVENT_SERVICE_PORT}
      USER_SERVICE_URL: http://user-service:4000/auth/validate
    depends_on:
      - postgres
      - user-service

  # frontend:
  #   build:
  #     context: ./packages/frontend
  #     args:
  #       NEXT_PUBLIC_USER_SERVICE_URL: ${NEXT_PUBLIC_USER_SERVICE_URL}
  #       NEXT_PUBLIC_EVENT_SERVICE_URL: ${NEXT_PUBLIC_EVENT_SERVICE_URL}
  #       NEXT_PUBLIC_FREELANCE_SERVICE_URL: ${NEXT_PUBLIC_FREELANCE_SERVICE_URL}
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   environment:
  #     NEXT_PUBLIC_USER_SERVICE_URL: ${NEXT_PUBLIC_USER_SERVICE_URL}
  #     NEXT_PUBLIC_EVENT_SERVICE_URL: ${NEXT_PUBLIC_EVENT_SERVICE_URL}
  #     NEXT_PUBLIC_FREELANCE_SERVICE_URL: ${NEXT_PUBLIC_FREELANCE_SERVICE_URL}
  #     USER_SERVICE_URL: http://user-service:4000/auth/validate
  #   depends_on:
  #     - postgres
  #     - user-service
  #     - freelance-service
  #     - event-service

volumes:
  pgdata:
