const responseStatusMap: { [key: string]: number } = {
  INTERNAL_SERVER_ERROR: 500,
  EVENT_NOT_FOUND: 404,
  EVENT_NOT_AVAILABLE: 400,
  ALREADY_REGISTERED: 409,
  ADDED_TO_WAITLIST: 200,
  SUCCESSFULLY_REGISTERED: 200,
  REGISTRATION_NOT_FOUND: 404,
  REGISTRATION_CANCELLED: 200,
  USER_ID_REQUIRED: 400,
  ATTENDEE_NOT_FOUND: 404,
  EVENT_DELETED: 200,
};

export default responseStatusMap;
